### ISSUE TITLE
Incorrect cd_SOURCE value for Blog newsletter sign-up

### ISSUE THREAD

**Issue by sdwilkes** [nationalarchives/tna-base#101]
The cd_SOURCE value for the newsletter sign-up on Blog (and AMP probably) should be 'blog' rather than 'web'. This is so marketing can see where users are signing up from.

Current value in tna-base:
<input type="hidden" name="cd_SOURCE" value="web">

From the old blog theme:

<input type="hidden" name="cd_SOURCE" value="blog">

**Comment by domingobishop** [comment]
No longer relevant as the sign up form has now changed to a new provider
