### ISSUE TITLE
Default mega menu incorrect html markup

### ISSUE THREAD

**Issue by netdesignr** [nationalarchives/tna-base#103]

**Comment by netdesignr** [comment]
When trying to install a new TNA-base Wordpress instance locally, if the file output.html is missing from the root of the website a default mega menu will show up. Unfortunately, the markup of the default mega menu is different to the live one, and therefore the styling won't be correct.

Default mega menu markup
![screencapture-github-nationalarchives-tna-base-blob-develop-inc-content-mega-menu-php-2018-09-17-15_02_24 copy](https://user-images.githubusercontent.com/5245264/45627678-5d65b580-ba8a-11e8-8bbf-317874a91411.png)

Live mega menu markup
![screen shot 2018-09-17 at 15 05 10](https://user-images.githubusercontent.com/5245264/45627700-69517780-ba8a-11e8-9003-e7931f127248.png)

**Comment by domingobishop** [comment]
Fixed during the rebrand process
