### ISSUE TITLE
Request a search for a certificate of British citizenship (W3C Validation Error)

### ISSUE THREAD

**Issue by AshTNA** [nationalarchives/tna-base#187]
http://contact.testlb.nationalarchives.gov.uk/request-a-search-for-a-certificate-of-british-citizenship-1949-1986/form/#step-1

- Empty action attribute on the form
- An alt tag on the submit button
- A `</p>` tag that doesn't have an opening tag
- An aria-labelledby that is not pointing to an element in the document

(These errors may be a result of the Javascript used to validate?)

There are also a couple accessibility issues, though I can't figure out what they mean: https://achecker.ca/checker/index.php

**Comment by domingobishop** [comment]
Moving this to tna-forms repo
