### ISSUE TITLE
Footer content order is different to live footer at smaller window sizes

### ISSUE THREAD

**Issue by mcieslak** [nationalarchives/tna-base#25]

**Comment by mcieslak** [comment]
Hi Chris, Your explanation makes sense, we have higher priority work to get on with than creating 2 different footers. The footer content order was originally defined by the editors based on user feedback but I feel as long as all the content in the footer is logical and easily accessible, the display order doesn't really matter and I don't think users will actually notice...So let's close this.

**Comment by SHudson1** [comment]
closing!
