### ISSUE TITLE
Problem with turning off the notification banner

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-base#32]
Currently when needing to remove the notification banner unchecking the box and clicking save just rechecks the box and doesn't remove the banner. In order to disable the banner we need to uncheck the box AND remove all the content from the boxes.

**Comment by domingobishop** [comment]
Can't seem to replicate the issue on my dev machine, but I made a fix which may rectify the issue.

**Comment by grange85** [comment]
Work around in place
