### ISSUE TITLE
Problem with direct link pages

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-base#35]
When we set a page to directly link to an external resource to show on the landing page these links don't go to the redriected resource in sub sections (I know that sounds confused so here's an example)...

On this page 
http://www.nationalarchives.gov.uk/archives-sector/archives-and-collections-online/

The link "Hospital Records Database" correctly goes to the redirected link

However on pages that are siblings to the redirect pages the sidebar renders the link to the page rather than to the resource - e.g. see the link to the "Hospital Records Database" on this page

http://www.nationalarchives.gov.uk/archives-sector/archives-and-collections-online/contributing-to-our-resources/

Give me a shout if that is still confused and you need a demo.

Cc: @SHudson1

**Comment by domingobishop** [comment]
I've put the fix onto develop. I rewrote it completely using a new hook, so it needs to be well tested.
